#!/bin/bash
# !/bin/bash -x to turn echo on 
# This is the script I use to start a remote clojure REPL running under docker.
# Once the REPL is running I connect to it on port 5007 using the "Connect to a running REPL in your project" in VSCode Calva.
docker run -p 5007:5007 -v $(pwd):$(pwd) -w $(pwd) mkersh65/clojure:version2 lein update-in :dependencies conj '[nrepl,"0.8.3"]' -- update-in :plugins conj '[cider/cider-nrepl,"0.26.0"]' -- update-in '[:repl-options,:nrepl-middleware]' conj '["cider.nrepl/cider-middleware"]' -- with-profile +dev repl :headless :host 0.0.0.0 :port 5007& 